export const SHOWS_FETCHED = 'SHOWS_FETCHED';
export const SHOWS_SEARCHED = 'SHOWS_SEARCHED';
export const SHOWS_SEARCH_CHANGED = 'SHOWS_SEARCH_CHANGED';
export const MOVIES_FETCHED = 'MOVIES_FETCHED_SUCCESSFULLY';
