export const SHOWS_FETCHED = 'SHOWS_FETCHED';
export const SHOWS_SEARCHED = 'SHOWS_SEARCHED';
export const SHOWS_SEARCH_CHANGED = 'SHOWS_SEARCH_CHANGED';
export const SHOWS_FIND_ONE = 'SHOWS_FIND_ONE';
export const SHOWS_FIND_LAST_EPISODE = 'SHOWS_FIND_LAST_EPISODE';
export const SHOWS_CLEAR_EPISODE = 'SHOWS_CLEAR_EPISODE';

export const MOVIES_FETCHED = 'MOVIES_FETCHED_SUCCESSFULLY';
